---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisService.name }}
spec:
  selector:
    app: {{ .Values.redisService.selectorLabels.app }}
  ports:
    - port: {{ .Values.redisService.port }}
      targetPort: {{ .Values.redisService.targetPort }}
  type: {{ .Values.redisService.type | default "ClusterIP" }}