apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tradebyte-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tradebyte-app
  minReplicas: 1   # Minimum pods
  maxReplicas: 10  # Maximum pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Scale when CPU hits 50% usage