apiVersion: v1
kind: Secret
metadata:
  name: tradebyte-secrets
type: Opaque
stringData:
  ENVIRONMENT: "DEV"
  HOST: "0.0.0.0"
  PORT: "80"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"